# Generated by Django 4.2.3 on 2023-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELC', 'Electronics'), ('FSH', 'Fashion'), ('TYS', 'Toys'), ('HOM', 'Home'), ('GRD', 'Gardening'), ('MSI', 'Musical instruments'), ('NON', 'other')], default='NON', max_length=64),
        ),
    ]
